apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dvwa-web
  namespace: dvwa-group02
subjects:
- kind: ServiceAccount
  name: sa-web
  namespace: dvwa-group02
roleRef:
  kind: Role
  name: role-dvwa
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dvwa-mysql
  namespace: dvwa-group02
subjects:
- kind: ServiceAccount
  name: sa-mysql
  namespace: dvwa-group02
roleRef:
  kind: Role
  name: role-dvwa
  apiGroup: rbac.authorization.k8s.io
