apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dvwa-mysql
  namespace: dvwa-group02-mysql
subjects:
- kind: ServiceAccount
  name: sa-mysql
  namespace: dvwa-group02-mysql
roleRef:
  kind: Role
  name: role-mysql
  apiGroup: rbac.authorization.k8s.io
