---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-mysql-service
  namespace: dvwa-group02-mysql
spec:
  selector:
    app: dvwa-mysql-grupo02
    tier: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
