apiVersion: v1
kind: PersistentVolume
metadata:
  name: dvwa-pv
  namespace: dvwa-group02-web
  labels:  # Add labels to the PV
    app: dvwa-grupo02  # Add the appropriate labels
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/www/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvwa-pvc
  namespace: dvwa-group02-web  # Specify your namespace here
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: dvwa-grupo02
  # You can add serviceAccountName if needed
